name: surf_cinema
description: A new Flutter application.

publish_to: 'none' #

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations: ^1.0.1

  get_it: ^5.0.1
  bloc: ^6.0.1
  flutter_bloc: ^6.0.1
  optional: ^5.0.0
  localized_string: ^0.1.0
  dio: ^3.0.9

  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

  flutter_launcher_icons: ^0.7.4

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  intl:
  intl_translation:

dev_dependencies:
  build_runner:
  hive_generator: ^0.7.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

